name: "Deploy Lab Manual pages"

on:
  push:
  workflow_dispatch:

permissions:
  id-token: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
      - run: nix build .#lab-help
      - uses: actions/upload-pages-artifact@v3
        with:
          path: result/share/lab-help/html/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/deploy-pages@v4
